# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0002_auto_20170411_1831'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
