# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0006_auto_20170729_1914'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
