# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-03 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0009_auto_20170908_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_for_post', to='MyBlog.Post'),
        ),
    ]
